### ISSUE TITLE
Move away from isomorphic-webcrypto

### ISSUE THREAD

**Issue by TimoGlastra** [digitalcredentials/jsonld-signatures#5]
It still depends on Expo unimodules, which has been deprecated for years and breaks React Native apps using Expo. We have to resort to quite cumbersome hacks to be able to build an Expo app using this library.

Sphereon has created a fork that removes this dependency, would it be possible to use this fork instead of isomorphic-webcrypto?

See https://github.com/Sphereon-Opensource/isomorphic-webcrypto

cc @nklomp

**Comment by dmitrizagidulin** [comment]
@TimoGlastra - Thanks for the heads up. Now that we know there's a Sphereon fork, we'll switch to that.

**Comment by dmitrizagidulin** [comment]
@TimoGlastra @nklomp - We've switched to the Sphereon fork, now published to npm as `@digitalcredentials/jsonld-signatures`@`10.0.0`.
Closing this issue for now, but feel free to reopen if it doesn't work or something else comes up.

**Comment by TimoGlastra** [comment]
Cool thanks! Are you intending to keep this branch alive for a while? https://github.com/digitalcredentials/jsonld.js/tree/v10.x

I want to upgrade, but then have to depend on this branch as well, I assume

**Comment by TimoGlastra** [comment]
Ah it seems the [digitalcredentials/jsonld.js@v10.x](https://github.com/digitalcredentials/jsonld.js/tree/v10.x?rgh-link-date=2024-02-08T05%3A41%3A42Z) mention in package.json does not work with Yarn 3. Do you think it'll be possible to publish this still for now a `@digitalcredentials/jsonld` on NPM until a new version of jsonld.js is released from DB that includes the required changes?

Update: it fails because when installing pack is called, which will call `prepack` which will call `build`. And that needs the devDependencies. But if you add a dependency, the dev dependencies are not installed. I think this can be resolved by making the `v10.x` branch include the already built files, and remove the `prepack`/`build` command

**Comment by dmitrizagidulin** [comment]
@TimoGlastra ah, yeah, lemme see what I can do.

**Comment by dmitrizagidulin** [comment]
@TimoGlastra @nklomp - hey, would it be possible to enable Issues on https://github.com/Sphereon-Opensource/isomorphic-webcrypto ? 
(I'm testing running the sphereon fork on React Native, and am running into a couple errors)
```
error: Error: Unable to resolve module crypto from ~/code/DCC/learner-credential-wallet/node_modules/asmcrypto.js/asmcrypto.all.js: crypto could not be found within the project or in these directories:
  node_modules
  4247 | function getRandomValues(buf) {
  4248 |     if (typeof process !== 'undefined') {
> 4249 |         var nodeCrypto = require('crypto');
       |                                   ^
  4250 |         var bytes = nodeCrypto.randomBytes(buf.length);
  4251 |         buf.set(bytes);
  4252 |         return;
    at ModuleResolver.resolveDependency (~/code/DCC/learner-credential-wallet/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:15)
    at DependencyGraph.resolveDependency (~/code/DCC/learner-credential-wallet/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (~/code/DCC/learner-credential-wallet/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (~/code/DCC/learner-credential-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at ~/code/DCC/learner-credential-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (~/code/DCC/learner-credential-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (~/code/DCC/learner-credential-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async addDependency (~/code/DCC/learner-credential-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
```
